"""gen tags

Revision ID: 02345cc3f9db
Revises: 
Create Date: 2025-12-10 00:19:17.675078

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02345cc3f9db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers')
    op.drop_table('shipments')
    op.drop_table('reviews')
    op.drop_table('shipment_tag')
    op.drop_table('shipment_events')
    op.drop_table('tags')
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('delivery_partners',
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('email_verified', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('serviceable_zipcodes', postgresql.ARRAY(
                        sa.INTEGER()), autoincrement=False, nullable=True),
                    sa.Column('max_handling_capacity', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name='delivery_partners_pkey'),
                    sa.UniqueConstraint('email', name='delivery_partners_email_key',
                                        postgresql_include=[], postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('sellers',
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('email_verified', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('address', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('zip_code', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('sellers_pkey')),
                    sa.UniqueConstraint('email', name=op.f('sellers_email_key'), postgresql_include=[
                    ], postgresql_nulls_not_distinct=False)
                    )

    op.create_table('shipments',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('content', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('destination', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('estimated_delivery', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('client_contact_email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('client_contact_phone', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('seller_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('delivery_partner_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['delivery_partner_id'], [
                        'delivery_partners.id'], name=op.f('shipments_delivery_partner_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['seller_id'], ['sellers.id'], name=op.f('shipments_seller_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey'))
                    )

    op.create_table('tags',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', postgresql.ENUM('FRAGILE', 'PERISHABLE', 'HEAVY', 'GIFT', 'electronics', 'DOCUMENTS', 'RETURN', 'EXPRESS',
                              'INTERNATIONAL', 'TEMPERATURE_CONTROLLED', 'STANDARD', name='tagnames'), autoincrement=False, nullable=False),
                    sa.Column('instruction', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
                    sa.UniqueConstraint('name', name='tags_name_key', postgresql_include=[
                    ], postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )

    op.create_table('shipment_events',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('location', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery',
                                                        'delivered', 'cancelled', name='shipmentstatus'), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('shipment_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f(
                        'shipment_events_shipment_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('shipment_events_pkey'))
                    )
    op.create_table('shipment_tag',
                    sa.Column('shipment_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('tag_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f(
                        'shipment_tag_shipment_id_fkey')),
                    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'],
                                            name=op.f('shipment_tag_tag_id_fkey')),
                    sa.PrimaryKeyConstraint('shipment_id', 'tag_id',
                                            name=op.f('shipment_tag_pkey'))
                    )
    op.create_table('reviews',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('rating', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('comment', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('shipment_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['shipment_id'], ['shipments.id'], name=op.f('reviews_shipment_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
                    )

    # ### end Alembic commands ###

    tags_table = sa.table(
        'tags',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.Enum(name='tagnames')),
        sa.column('instruction', sa.String()),
    )

    op.bulk_insert(
        tags_table,
        [
            {
                "id": uuid4(),
                "name": "FRAGILE",
                "instruction": "Handle with care, no stacking, cushion during transit.",
            },
            {
                "id": uuid4(),
                "name": "PERISHABLE",
                "instruction": "Keep cool, minimize transit time, avoid direct sunlight.",
            },
            {
                "id": uuid4(),
                "name": "HEAVY",
                "instruction": "Team lift recommended; secure to prevent shifting.",
            },
            {
                "id": uuid4(),
                "name": "GIFT",
                "instruction": "Do not reveal contents; maintain packaging presentation.",
            },
            {
                "id": uuid4(),
                "name": "electronics",
                "instruction": "Protect from moisture; avoid magnetic fields; keep upright.",
            },
            {
                "id": uuid4(),
                "name": "EXPRESS",
                "instruction": "Priority handling; use fastest route; confirm delivery quickly.",
            },
            {
                "id": uuid4(),
                "name": "INTERNATIONAL",
                "instruction": "Include customs docs; verify destination restrictions.",
            },
            {
                "id": uuid4(),
                "name": "TEMPERATURE_CONTROLLED",
                "instruction": "Maintain within specified temperature band; monitor during transit.",
            },
            {
                "id": uuid4(),
                "name": "STANDARD",
                "instruction": "Routine handling; follow default packaging guidelines.",
            },
        ],
    )
