"""user verif

Revision ID: 0ad08dc18736
Revises: 6bde8efbc0f7
Create Date: 2025-11-30 22:42:03.986669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ad08dc18736'
down_revision: Union[str, Sequence[str], None] = '6bde8efbc0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_events')
    op.drop_table('shipments')
    op.drop_table('sellers')
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('address', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('zip_code', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='sellers_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('delivery_partners',
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('serviceable_zipcodes', postgresql.ARRAY(
                        sa.INTEGER()), autoincrement=False, nullable=True),
                    sa.Column('max_handling_capacity', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name='delivery_partners_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('shipments',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('content', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('destination', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('estimated_delivery', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('seller_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('delivery_partner_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['delivery_partner_id'], [
                        'delivery_partners.id'], name='shipments_delivery_partner_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['seller_id'], ['sellers.id'], name='shipments_seller_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='shipments_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('shipment_events',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('location', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery',
                                                        'delivered', 'cancelled', name='shipmentstatus'), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('shipment_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f(
                        'shipment_events_shipment_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('shipment_events_pkey'))
                    )
    # ### end Alembic commands ###
