"""adding shipment event

Revision ID: 6bde8efbc0f7
Revises: bd511f3759df
Create Date: 2025-11-22 19:52:02.608097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bde8efbc0f7'
down_revision: Union[str, Sequence[str], None] = 'bd511f3759df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('sellers')
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('content', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('destination', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery',
                                                        'delivered', name='shipmentstatus'), autoincrement=False, nullable=False),
                    sa.Column('estimated_delivery', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('seller_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('delivery_partner_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['delivery_partner_id'], [
                        'delivery_partners.id'], name=op.f('shipments_delivery_partner_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['seller_id'], ['sellers.id'], name=op.f('shipments_seller_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey'))
                    )
    op.create_table('delivery_partners',
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('serviceable_zipcodes', postgresql.ARRAY(
                        sa.INTEGER()), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('delivery_partners_pkey'))
                    )
    op.create_table('sellers',
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('sellers_pkey'))
                    )
    # ### end Alembic commands ###
